language: python
branches:
  only:
  - master
  - "/^\\d\\.\\d+$/"
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
  - python: 3.8
    env: TOXENV=py38
  - python: 3.6
    env: TOXENV=train
  - python: 3.7
    env: TOXENV=train
  - python: 3.8
    env: TOXENV=train
install:
- pip install -U pip tox codecov twine wheel
script: tox
after_success:
- codecov
cache:
  directories:
  - "$HOME/.cache/pip"
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: OZa/cW2LTE2EmQM1gyr5gtbRHp7nsQytqgWwsqh/t7ql3OKJNhUk+N9hCl17YkMySTMnc54nK+oAfmrOyn9ezuSjQ/ZoDoY/CZRa4lZ4pqVa342neEw3u6eQ81+Oiz7uIGqeKvRuHCA50T2N00nBcqRtlVOnPg7zXh61NbnawpK3dw3Q3LdqZAoYqA111eO3Qpicl+N3QNxIon03UQkF34n1WHYWabDxzDEEdYK06tlZWF5bq2Xijn8klLTY2we1HQ7Dhq11gxdu8R7k3ZXrz0OG56Vnv0BW302qZhor+73BSRz8+UPuoYkiEDol6e6CLD6BWjgLfL2D9V2p7Xlwdsc5yEW8QIZ9BH3WKreQlGtDkkUU6hkLxUC1sCc1UPP7vftbIRMZ9iT596oAE89fpjRXvEi+LtG2GOnE16HmzrUesOouObHXwsVIh744EmLsvw+EZ8ze5i9YKForUb3vfQrKktm6cf9n4pqjwFC1618ziCMhPnPTBUhmxk54f4PJ6nilXUzTTkQEt+MXpuWUN51nOe0rQLupWkvu538QG29Wmx6enHsfyUnxqswhrv+wKWY/Frl/jmPLKJoZ7/FqXErLoOPL/U9Zopwkr7YL0vULf3yhKevR5m89Yxk0lGD49KmfHwsUHgDe20cwsExaYiFRRv8F/VnkSanPPm5Pnm0=
  skip_existing: true
  on:
    branch: master
