language: python
branches:
  only:
  - master
  - "/^\\d\\.\\d+$/"
matrix:
  include:
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
  - python: 3.8
    env: TOXENV=py38
  - python: 3.5
    env: TOXENV=train
  - python: 3.6
    env: TOXENV=train
  - python: 3.7
    env: TOXENV=train
  - python: 3.8
    env: TOXENV=train
install:
- pip install -U pip tox codecov twine wheel
script: tox
after_success:
- codecov
cache:
  directories:
  - "$HOME/.cache/pip"

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: p1Yll5ymYvgBZsKAhzphiQGxXO3bne/KsMvfsG+mcMi7+5M81As8bYTQMl3zHwmBsicyO1FT+pskpGkPZHqvkzp+z35b+dy8jAht+a5zQQ6K1Mbv7gWlBxWrkNEXH4SItFUAM0qxdIpPdiJfOWzpYFZIxknZDVXdj3iZe3PByXgzSZkJW5TrJRJplrI14puuU3gSuOO2JqF3bHYGM7fJgXNDA8/FeIIX5gHdQfTr9QbHPF39B165lhMD7wX/5Rh979xgyKZLoiyEnyLMg/ybUJ2afrP4hznR+wiRU5Lnky853xudm0PFZeo1q7GorZ4h8v46mVoQ6jE3imsm7JQOEZqCnr6WJQ1WzLEANFwHWfVS8PvIbk13IHlBrMilkKbxE3SdIQ/BTKxkJIDFWwEGmv50dfmiAAbQSeztU4PMuBfVJ2fKjWKGVdE9HzB3vlC7BoE8b9UaSBowJH5vNgq9oD+z0fKmMjLl+xafAOBBHarZBCHmKPzwuIkcl4ZURzkW4qfXdHQnXuhPuAoAiKjK48MHiFVDlXmxNPXj5hXWsHjOgKiHNDbrQOGha4VRYkqyVvZkir4bQT1P2kIus9mOtXWySOTdnaYYW5hvQHoH7V3s5R2AHnQBmbw8zOoOUs1RZQu4BOgmIDWnGVqcuT9wA9/iPT30xay6YQYU4ihsT1c=
  on:
    branch: master